version: "3.8"

services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: education_backend:latest
    depends_on:
      - db
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: education_frontend:latest
    ports:
      - "8082:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  proxy:
    image: education_proxy:latest
    ports:
      - "8088:80"
    depends_on:
      - backend
      - frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure